### ISSUE TITLE
Could you share the visualization code?

### ISSUE THREAD

**Issue by AcodeC** [shvdiwnkozbw/Video-Representation-via-Multi-level-Optimization#1]
Thank you for your awesome work. Could you share the visualization code?

**Comment by shvdiwnkozbw** [comment]
Thanks for your attention. We have uploaded the visualization procedure and code in ./visualization, with illustration in README.

**Comment by AcodeC** [comment]
> Thanks for your attention. We have uploaded the visualization procedure and code in ./visualization, with illustration in README.

Thank you very much!
